name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-20.04
    steps:
      - name: Release please
        id: release_please
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          default-branch: main
          release-type: python
          package-name: calcs
      - name: Checkout code
        if: steps.release_please.outputs.release_created
        uses: actions/checkout@v2
      - name: Build
        if: steps.release_please.outputs.release_created
        run: python3 calc/generate_data.py
      - name: Zip calcs
        if: steps.release_please.outputs.release_created
        run: |
          zip -FSry calcs.zip txt
      - name: Upload calss
        if: steps.release_please.outputs.release_created
        uses: AButler/upload-release-assets@v2.0
        with:
          files: calcs.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.release_please.outputs.tag_name }}
